name: Node.js Package

on:
  push:
    paths:
      - '*.ts'
      - '*.js'
      - '*.json'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: linting and testing
        run: |
          npm ci
          npm run build
          npm run typecheck
          npm run lint
          npm run test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
